spring:
  application:
    name: carbonlease
  datasource:
    url: jdbc:oracle:thin:@115.90.212.20:10000:XE
    username: PSH07
    password: PSH071234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    
server:
  port: 80
  
mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package:
  mapper-locations: classpath:mapper/*.xml